// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gosmsjuyecldsbanltov.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdvc21zanV5ZWNsZHNiYW5sdG92Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxMjU0NTAsImV4cCI6MjA3NDcwMTQ1MH0.o3lC4SvSI_gV-e4ipaRKAxYCibMXgASZozSmfT9cDMo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});